language: cpp 
os: 
    - linux
    - osx
compiler:
    - gcc
    - clang
addons:
  apt:
    packages:
      - g++-6
      - clang-4.0
    sources: &sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-4.0

before_install:
    - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe multiverse"
    - sudo apt-get update
    - if [[ $CXX == 'clang++' ]]; then export CXX=clang++-4.0; fi
    - if [[ $CXX == 'g++'     ]]; then export CXX=g++-6; fi
install:
    - sudo apt-get install --no-install-recommends libhdf5-7
    - sudo apt-get install --no-install-recommends libpango-1.0-0 libpangocairo-1.0-0 libhdf5-dev
    - sudo apt-get install --no-install-recommends -t trusty -y libboost-thread-dev libboost-timer-dev libblitz0-dev libhdf5-serial-dev cmake 

    # libmpdata
    - cd ..
    - git clone --depth=1 git://github.com/igfuw/libmpdataxx.git
    - cd libmpdataxx/libmpdata++
    - mkdir build
    - cd build
    - cmake ..
    - sudo cmake -P cmake_install.cmake

script:
    - cd ../../../shallow-water-elliptic-drop
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ../
    - make
    - cmake -DCMAKE_BUILD_TYPE=Release ../
    - make
    # TODO: unit tests / run the simulation
